# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeedRideDriver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeedRideDriver

pod 'Alamofire'
   pod 'SwiftyJSON'
   pod 'SDWebImage'
   pod 'SVProgressHUD'
   pod 'Toaster'
   pod 'NVActivityIndicatorView'
   pod 'KWVerificationCodeView'

   pod 'FBSDKLoginKit'
   pod 'FBSDKCoreKit'

   pod 'Socket.IO-Client-Swift', '~> 15.2.0'

   pod 'GoogleSignIn'
   pod 'GooglePlaces'
   pod 'GoogleMaps'

   #pod 'Firebase'
   pod 'FirebaseAnalytics'
   pod 'FirebaseMessaging'

  target 'SpeedRideDriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpeedRideDriverUITests' do
    # Pods for testing
  end

end
