# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'SpeedRideCustomer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RidexCustomer
    
    pod 'SwiftyJSON'
    pod 'NVActivityIndicatorView'
    pod 'KWVerificationCodeView'

    pod 'FirebaseCrashlytics'
    pod 'FirebaseAnalytics'

    pod 'GoogleSignIn'
    pod 'GooglePlaces'
    pod 'GoogleMaps'

    pod 'FBSDKLoginKit'
    pod 'FBSDKCoreKit'

    pod 'Alamofire' #, '~> 4.8.2'
    pod 'SVProgressHUD'
    pod 'Toaster'
    pod 'Socket.IO-Client-Swift'
    pod 'SDWebImage', '~> 5.0'

    pod 'StripePaymentsUI'
    pod 'Stripe'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

    end
  end
end
