package com.speedride.driver.utils

object Common {
    const val REQUEST_GPS_CHECK_SETTINGS = 100
    //const val BASE_URL = "https://ded3896.inmotionhosting.com/~mobile/ridex-backend/api/v1/" // "https://ded3138.inmotionhosting.com/~mobile/ridex-backend/api/v1/"
    //const val BASE_URL = "http://54.184.120.212/api/v1/" // "https://ded3138.inmotionhosting.com/~mobile/ridex-backend/api/v1/"
    const val BASE_URL = "https://speedridellc.com/api/v1/" // "https://ded3138.inmotionhosting.com/~mobile/ridex-backend/api/v1/"

    //    public static final String BASE_URL = "http://192.249.121.94/~mobile/citycab/api/v1/";
    const val API_KEY = "oKRsI6LcIUjw242zsVTRn0hCSe7U3C"

    //public static final String UPLOAD_URL = "http://192.249.121.94/~mobile/citycab/public/upload/";

    const val LOGIN_TYPE_GOOGLE = "google"
   // const val UPLOAD_URL =  "https://ded3896.inmotionhosting.com/~mobile/ridex-backend/public/upload/" // ""https://ded3138.inmotionhosting.com/~mobile/ridex-backend/public/upload/" // "http://205.134.254.135/~mobile/ridex-backend/upload/" // "http://205.134.254.135/~mobile/citycab-backend/upload/"
    const val UPLOAD_URL =  "https://speedridellc.com/upload/" // ""https://ded3138.inmotionhosting.com/~mobile/ridex-backend/public/upload/" // "http://205.134.254.135/~mobile/ridex-backend/upload/" // "http://205.134.254.135/~mobile/citycab-backend/upload/"
    const val UPDATE_LATITUDE_LONGITUDE = "extra_latitude"
    const val CONNECT_SOCKET = "connect_socket"
    const val DISCONNECT_SOCKET = "disconnect_socket"
    const val ROLE_DRIVER = "Driver"
   const val ANDROID = "Android"
    const val FRAGMENT_POSITION = "documentFragmentPosition"
    const val LOGIN_TYPE_NORMAL = "normal"
    const val LOGIN_TYPE_FACEBOOK = "facebook"
    const val DRIVER_ONLINE_ON = "on"
    const val DRIVER_ONLINE_OFF = "off"
    const val FRAGMENT_ON_GOING = "fragment_on_going"
    const val FRAGMENT_COLLECT_CASH = "fragment_collect_cash"
    const val FRAGMENT_REVIEW_TRIP = "fragment_review_trip"
    const val DOC_LICENCE = "Licence"
    const val DOC_INSURANCE = "Insurance"
    const val DOC_PERMIT = "Permit"
    const val DOC_REGISTRATION = "Registration"
    const val RIDE_REQUEST_FROM_CUSTOMER = "ride_request_from_customer"
    const val RIDE_REQUEST_REJECT = "ride_request_reject"
    const val RIDE_REQUEST_ACCEPT = "ride_request_accept"
    const val NOTIFY_RIDE_CANCEL_DETAILS = "ride_cancel_details"
    const val NEW_SHARED_RIDE_DETAILS = "new_shared_ride_details"
    const val EARNING_TYPE_TODAY = "today"
    const val EARNING_TYPE_WEEKLY = "weekly"
    const val TRIP_COMPLETED = "Completed"
    const val TRIP_CANCEL = "Cancel"
    const val PAYMENT_MODE_CASH = "Cash"
    const val PAYMENT_MODE_PAYPAL = "Paypal"
    const val PAYMENT_MODE_CREDIT_DEBIT_CARD = "Credit/Debit Card"
    const val STATUS_200 = 200
    //const val OTHER_IMAGE_URL =  "https://ded3896.inmotionhosting.com/~mobile/ridex-backend/"
    const val OTHER_IMAGE_URL =  "https://speedridellc.com/upload/"
    const val RECIEVE_CHAT_MESSAGE = "recieve_message"
    const val MESSAGE_TYPE_TEXT = "text"
    const val MESSAGE_TYPE_IMAGE = "image"
    const val SEND_MESSAGE_CHAT = "send_message_to_chat"
    const val SEND_MESSAGE_TO_ADMIN_CHAT = "send_message_to_chat_to_admin"
    const val RECIEVE_CHAT_MESSAGE_TO_ADMIN = "recieve_message_to_admin"
    const val RIDE_PENDING = "Pending"
    const val RIDE_RIDING = "Riding"
    const val RIDE_CONFIRM = "Confirmed"
    const val RIDE_COMPLETE = "Completed"
    const val ENABLE = "Enable"
    const val Done = "Done"
    const val PRIVACY_POLICY = "https://speedridellc.com/privacypolicy"
}